# Gui constants
TIMER_WIDTH = 200
TIMER_HEIGHT = 100

IDLE_TEXT = "--"

BOMB_TIME = 40
HURRY_UP_THRESHOLD = 15
WITHOUT_DEFUSER_THRESHOLD = 10
WITH_DEFUSER_THRESHOLD = 5

BG_COLOUR = "#2D2D2D"
FG_COLOUR = "#00CC00"

HURRY_UP_COLOUR = "#FFCC00"
WITHOUT_DEFUSER_COLOUR = "#FFCC00"
WITH_DEFUSER_COLOUR = "#FF4D4D"

FONT = ("Helvetica", 36, "bold")
TEXT_POSITION = (TIMER_WIDTH / 2, TIMER_HEIGHT / 2)

GUI_CHECK_MSG_INTERVAL = 100
DEBUG_ENABLED = False
